### ISSUE TITLE
Add the ability to remove phrases as well as add

### ISSUE THREAD

**Issue by lewisnyman** [hubot-scripts/hubot-business-cat#21]
Hi, Love the plugin ❤️🐈

There are a few phrases that we like "ping me" that don't feel very corporate, maybe we can also have a way to remove or replace the list of phases as well as just adding? I can work on a PR for this.

**Comment by okize** [comment]
@lewisnyman That's a good idea! PRs are very welcome; I can probably get to it next week otherwise.

Also, I think "ping me" should probably be removed, that one triggers constantly for us.

**Comment by scit106** [comment]
I actually just added this, see #22

**Comment by okize** [comment]
@lewisnyman does https://github.com/hubot-scripts/hubot-business-cat/pull/22 satisfy this issue for you?

**Comment by lewisnyman** [comment]
That's great, thank you! Looks like we need to update the readme
