### ISSUE TITLE
Triggers on non-listed words

### ISSUE THREAD

**Issue by timfallmk** [hubot-scripts/hubot-business-cat#7]
We're using this tool-of-high-productivity in Slack, but we're getting triggers against variations of the word "droid". As you can imagine it also picks up all "Android" references.

I don't see that in the trigger list. Any ideas?

**Comment by okize** [comment]
Oops! This was happening because I neglected to add word boundaries to "ROI".

This was a great catch, thanks so much for opening an issue! The fix has been published to v1.1.15

**Comment by timfallmk** [comment]
:+1:
